added script to stop the container and limited the CPU, memomry and memory swap

diff --git a/roles/pihole/templates/pihole.sh.j2 b/roles/pihole/templates/pihole.sh.j2
--- a/roles/pihole/templates/pihole.sh.j2
+++ b/roles/pihole/templates/pihole.sh.j2
@@ -3,7 +3,7 @@
 # https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
 
 PIHOLE_BASE="{{ pihole_base }}"
-[[ -d "$PIHOLE_BASE" ]] || mkdir -p "$PIHOLE_BASE" || { echo "Couldn't create storage directory: $PIHOLE_BASE"; exit 1; }
+[[ -d "$PIHOLE_BASE" ]] || mkdir -p "$PIHOLE_BASE" || {{ "{" }} echo "Couldn't create storage directory: $PIHOLE_BASE"; exit 1; {{ "}" }}
 
 # Note: ServerIP should be replaced with your external ip.
 docker run -d \
@@ -19,12 +19,12 @@ docker run -d \
     -e VIRTUAL_HOST="pi.hole" \
     -e PROXY_LOCATION="pi.hole" \
     -e ServerIP="{{ ansible_default_ipv4.address }}" \
-    --memory=256M --cpus=0.1 \
+    --memory={{ container.memory }} --memory-swap={{ container.memory_swap }} --cpus={{ container.cpu }} \
     pihole/pihole:latest
 
 printf 'Starting up pihole container '
-for i in $(seq 1 20); do
-    if [ "$(docker inspect -f "{{.State.Health.Status}}" pihole)" == "healthy" ] ; then
+for i in $(seq 1 {{ stand_up_retries }}); do
+    if [ "$(docker inspect -f "{{ "{{" }}.State.Health.Status{{ "}}" }}" pihole)" == "healthy" ] ; then
         printf ' OK'
         echo -e "\n$(docker logs pihole 2> /dev/null | grep 'password:') for your pi-hole: https://{{ ansible_default_ipv4.address }}/admin/"
         exit 0
@@ -33,7 +33,7 @@ for i in $(seq 1 20); do
         printf '.'
     fi
 
-    if [ $i -eq 20 ] ; then
+    if [ $i -eq {{ stand_up_retries }} ] ; then
         echo -e "\nTimed out waiting for Pi-hole start, consult check your container logs for more info (\`docker logs pihole\`)"
         exit 1
     fi
